services:
  - type: web
    name: django-backend
    env: python
    plan: free  # change if you use starter/standard
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn website.wsgi:application --bind 0.0.0.0:$PORT
    runtime:
      python: 3.11.9
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: website.settings
