# Generated by Django 5.2.6 on 2025-09-24 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_users_email_alter_users_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authuser',
            name='first_name',
        ),
    ]
