# Generated by Django 5.2.6 on 2025-09-24 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_remove_authuser_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authuser',
            name='last_name',
        ),
    ]
